from typing import Callable

from nicegui import ui

from callbacks import Callbacks
from configuration import Config

from .step_base import BaseStep

HELP_TEXT = (
    "- **Review Config**: Review the compiled configuration generated by the "
    "wizard.\n"
    "- **Check Syntax**: Validate INI syntax before persisting.\n"
    "- **Save Config**: Save configuration to `config.ini` and write "
    "reference marker images to disk.\n"
    "- **Take In Use**: Apply the new configuration directly to active "
    "system runtime."
)


class FinalStep(BaseStep):
    def __init__(
        self,
        name: str,
        callbacks: Callbacks,
        set_image_callback: Callable[[str], None],
        save_refs_func: Callable[[], None],
        spinner=None,
    ) -> None:
        super().__init__(
            name,
            set_image_callback=set_image_callback,
            spinner=spinner,
        )
        self.save_refs_func = save_refs_func
        self.callbacks = callbacks
        self.editor: ui.textarea
        self.new_config_saved = False
        self.txt = ""

    def set_config(self, config: Config) -> None:
        self.editor.value = config.save_to_string()
        self.txt = self.editor.value

    def _save_config(self) -> None:
        if self._syntax_check() is True:
            self.save_refs_func()
            self.callbacks.save_config_file(self.editor.value)
            self.new_config_saved = True
            ui.notify("Config saved", type="positive")
        self.txt = self.editor.value

    def _show_config(self) -> None:
        try:
            config = Config()
            config.load_from_string(self.editor.value)
            j = config.model_dump_json(indent=4)
            with ui.dialog() as dialog:
                with ui.card().classes(
                    "bg-slate-900 border border-white/10 rounded-2xl p-4 "
                    "max-w-4xl w-full"
                ):
                    with ui.row().classes(
                        "w-full items-center justify-between pb-2 border-b "
                        "border-white/10"
                    ):
                        ui.label("Compiled Config (JSON)").classes(
                            "font-semibold text-slate-200"
                        )
                        ui.button(icon="close", on_click=dialog.close).props(
                            "flat round dense"
                        )
                    ui.code(j, language="json").classes(
                        "w-full max-h-[70vh] overflow-auto text-xs rounded-xl"
                    )
            dialog.open()
        except Exception as e:
            ui.notify(f"Syntax error: {e}", type="negative")

    def _use_config(self) -> None:
        self.callbacks.use_config()
        self.new_config_saved = False
        ui.notify("Config taken in use", type="positive")

    def _syntax_check(self) -> bool:
        try:
            config = Config()
            config.load_from_string(self.editor.value)
            ui.notify("Syntax is correct", type="positive")
            return True
        except Exception as e:
            ui.notify(f"Syntax error: {e}", type="negative")
            return False

    async def show(self, stepper, first_step=False, last_step=False) -> None:
        with ui.step(self.name):
            self.add_help(HELP_TEXT)

            with ui.card().classes(
                "w-full bg-slate-900/60 border border-white/10 rounded-xl p-3 my-2"
            ):
                with ui.row().classes(
                    "w-full items-center justify-between gap-2 flex-wrap"
                ):
                    with ui.row().classes("items-center gap-2"):
                        ui.button(
                            "Check Syntax",
                            icon="verified",
                            on_click=self._syntax_check,
                        ).props("outline dense").classes("text-slate-300 font-medium")

                        ui.button(
                            "JSON Preview",
                            icon="code",
                            on_click=self._show_config,
                        ).props("outline dense").classes("text-slate-300 font-medium")

                    with ui.row().classes("items-center gap-2"):
                        self.button_save = (
                            ui.button(
                                "Save Config",
                                icon="save",
                                on_click=self._save_config,
                            )
                            .props("unelevated dense")
                            .classes(
                                "bg-emerald-600 hover:bg-emerald-500 text-white "
                                "px-3 font-medium shadow-md"
                            )
                            .tooltip("Save configuration and marker images to disk")
                        )

                        self.button_use_config = (
                            ui.button(
                                "Take In Use",
                                icon="play_circle",
                                on_click=self._use_config,
                            )
                            .props("unelevated dense")
                            .classes(
                                "bg-gradient-to-r from-blue-600 to-indigo-600 "
                                "hover:from-blue-500 hover:to-indigo-500 text-white "
                                "px-3 font-medium shadow-md"
                            )
                            .tooltip(
                                "Apply configuration immediately to live system runtime"
                            )
                        )

            with ui.card().classes(
                "w-full bg-slate-950/80 border border-white/10 rounded-xl "
                "p-2 my-2 shadow-inner"
            ):
                self.editor = (
                    ui.textarea()
                    .classes("w-full font-mono text-xs text-slate-200")
                    .props("autoResize rows=22 spellcheck=false")
                )

            super().add_navigator(stepper, first_step, last_step)
