import logging
from collections.abc import Callable

from nicegui import ui

from callbacks import Callbacks
from configuration import Config

from .step_base import BaseStep

logger = logging.getLogger(__name__)

HELP_TEXT = (
    "- **Review Config**: Review the compiled configuration generated by the "
    "wizard.\n"
    "- **Check Syntax**: Validate INI syntax before persisting.\n"
    "- **Save Config**: Save configuration to `config.ini` and write "
    "reference marker images to disk.\n"
    "- **Take In Use**: Apply the new configuration directly to active "
    "system runtime."
)


class FinalStep(BaseStep):
    def __init__(
        self,
        name: str,
        callbacks: Callbacks,
        set_image_callback: Callable[[str], None],
        save_refs_func: Callable[[], None],
        spinner=None,
    ) -> None:
        super().__init__(
            name,
            set_image_callback=set_image_callback,
            spinner=spinner,
        )
        self.save_refs_func = save_refs_func
        self.callbacks = callbacks
        self.editor: ui.textarea
        self.new_config_saved = False
        self.txt = ""
        self.status_banner: ui.row | None = None
        self.status_icon: ui.icon | None = None
        self.status_label: ui.label | None = None

    def update_status_banner(self) -> None:
        if (
            self.status_banner is None
            or self.status_label is None
            or self.status_icon is None
        ):
            return
        if self.new_config_saved:
            self.status_banner.classes(
                "bg-emerald-950/40 border-emerald-500/40 text-emerald-200",
                remove="bg-amber-950/40 border-amber-500/40 text-amber-200",
            )
            self.status_icon.props("name=check_circle color=emerald")
            self.status_label.text = (
                "Configuration and reference templates successfully saved to disk. "
                "Click 'Take In Use' to apply changes immediately to running services."
            )
        else:
            self.status_banner.classes(
                "bg-amber-950/40 border-amber-500/40 text-amber-200",
                remove="bg-emerald-950/40 border-emerald-500/40 text-emerald-200",
            )
            self.status_icon.props("name=pending_actions color=amber")
            self.status_label.text = (
                "Configuration not yet saved. Review the generated configuration below "
                "and click 'Save Config' when ready to write files to disk."
            )

    def _on_editor_changed(self, value: str) -> None:
        if self.new_config_saved and value != self.txt:
            self.new_config_saved = False
            self.update_status_banner()

    def set_config(self, config: Config) -> None:
        self.editor.value = config.save_to_string()
        self.txt = self.editor.value
        self.new_config_saved = False
        self.update_status_banner()

    def _prompt_hot_reload(self) -> None:
        try:
            with (
                ui.dialog() as reload_dialog,
                ui.card().classes(
                    "bg-slate-900 border border-white/10 rounded-2xl p-5 "
                    "max-w-md w-full gap-4"
                ),
            ):
                with ui.row().classes("items-center gap-3"):
                    with ui.element("div").classes(
                        "w-10 h-10 rounded-xl bg-blue-500/20 "
                        "border border-blue-500/30 flex items-center "
                        "justify-center text-blue-400"
                    ):
                        ui.icon("autorenew", size="md")
                    with ui.column().classes("gap-0"):
                        ui.label("Configuration Saved").classes(
                            "text-base font-bold text-slate-100"
                        )
                        ui.label("Take new configuration in use?").classes(
                            "text-xs text-slate-400"
                        )
                ui.label(
                    "Configuration and reference templates have been saved to disk. "
                    "Would you like to hot-reload running services now with the new configuration?"
                ).classes("text-sm text-slate-300 leading-relaxed")

                def on_hot_reload() -> None:
                    reload_dialog.close()
                    self._use_config()

                with ui.row().classes("w-full justify-end items-center gap-2 mt-2"):
                    ui.button("Later", on_click=reload_dialog.close).props(
                        "flat dense"
                    ).classes("text-slate-400 hover:text-slate-200")
                    ui.button(
                        "Hot Reload Now",
                        icon="autorenew",
                        on_click=on_hot_reload,
                    ).props("unelevated dense").classes(
                        "bg-gradient-to-r from-blue-600 to-indigo-600 "
                        "hover:from-blue-500 hover:to-indigo-500 text-white "
                        "px-4 py-1.5 rounded-xl font-medium shadow-md shadow-blue-950/50"
                    )
            reload_dialog.open()
        except Exception as e:
            logger.debug(f"Could not open hot reload dialog: {e}")

    def _save_config(self) -> None:
        if self._syntax_check() is True:
            self.save_refs_func()
            self.callbacks.save_config_file(self.editor.value)
            self.new_config_saved = True
            self.update_status_banner()
            ui.notify("Config saved", type="positive")
            self._prompt_hot_reload()
        self.txt = self.editor.value

    def _show_config(self) -> None:
        try:
            config = Config()
            config.load_from_string(self.editor.value)
            j = config.model_dump_json(indent=4)
            with (
                ui.dialog() as dialog,
                ui.card().classes(
                    "bg-slate-900 border border-white/10 rounded-2xl p-4 "
                    "max-w-4xl w-full"
                ),
            ):
                with ui.row().classes(
                    "w-full items-center justify-between pb-2 border-b "
                    "border-white/10"
                ):
                    ui.label("Compiled Config (JSON)").classes(
                        "font-semibold text-slate-200"
                    )
                    ui.button(icon="close", on_click=dialog.close).props(
                        "flat round dense"
                    )
                ui.code(j, language="json").classes(
                    "w-full max-h-[70vh] overflow-auto text-xs rounded-xl"
                )
            dialog.open()
        except Exception as e:
            ui.notify(f"Syntax error: {e}", type="negative")

    def _use_config(self) -> None:
        self.callbacks.use_config()
        self.new_config_saved = False
        self.update_status_banner()
        ui.notify("Config taken in use", type="positive")

    def _syntax_check(self) -> bool:
        try:
            config = Config()
            config.load_from_string(self.editor.value)
            ui.notify("Syntax is correct", type="positive")
            return True
        except Exception as e:
            ui.notify(f"Syntax error: {e}", type="negative")
            return False

    async def show(self, stepper, first_step=False, last_step=False) -> None:
        with ui.step(self.name):
            self.add_help(HELP_TEXT)

            with (
                ui.row()
                .classes(
                    "w-full px-4 py-3 rounded-xl border transition-all items-center "
                    "gap-3 mb-2 bg-amber-950/40 border-amber-500/40 text-amber-200"
                )
                .props('id="final-step-status-banner"') as self.status_banner
            ):
                self.status_icon = ui.icon("pending_actions", color="amber").classes(
                    "text-xl shrink-0"
                )
                self.status_label = ui.label(
                    "Configuration not yet saved. Review the generated configuration below "
                    "and click 'Save Config' when ready to write files to disk."
                ).classes("text-xs font-semibold leading-normal flex-1")

            with (
                ui.card().classes(
                    "w-full bg-slate-900/60 border border-white/10 rounded-xl p-3 my-2"
                ),
                ui.row().classes("w-full items-center justify-between gap-2 flex-wrap"),
            ):
                with ui.row().classes("items-center gap-2"):
                    ui.button(
                        "Check Syntax",
                        icon="verified",
                        on_click=self._syntax_check,
                    ).props("outline dense").classes("text-slate-300 font-medium")

                    ui.button(
                        "JSON Preview",
                        icon="code",
                        on_click=self._show_config,
                    ).props("outline dense").classes("text-slate-300 font-medium")

                with ui.row().classes("items-center gap-2"):
                    self.button_save = (
                        ui.button(
                            "Save Config",
                            icon="save",
                            on_click=self._save_config,
                        )
                        .props("unelevated dense")
                        .classes(
                            "bg-emerald-600 hover:bg-emerald-500 text-white "
                            "px-3 font-medium shadow-md"
                        )
                        .tooltip("Save configuration and marker images to disk")
                    )

                    self.button_use_config = (
                        ui.button(
                            "Take In Use",
                            icon="play_circle",
                            on_click=self._use_config,
                        )
                        .props("unelevated dense")
                        .classes(
                            "bg-gradient-to-r from-blue-600 to-indigo-600 "
                            "hover:from-blue-500 hover:to-indigo-500 text-white "
                            "px-3 font-medium shadow-md"
                        )
                        .tooltip(
                            "Apply configuration immediately to live system runtime"
                        )
                    )

            with ui.card().classes(
                "w-full bg-slate-950/80 border border-white/10 rounded-xl "
                "p-2 my-2 shadow-inner"
            ):
                self.editor = (
                    ui.textarea(on_change=lambda e: self._on_editor_changed(e.value))
                    .classes("w-full font-mono text-xs text-slate-200")
                    .props("autoResize rows=22 spellcheck=false")
                )

            self.update_status_banner()
            super().add_navigator(stepper, first_step, last_step)
