import base64
import logging
from collections.abc import Callable

from nicegui import ui

from callbacks import Callbacks
from configuration import Config
from gui.components import (
    ValidationBanner,
    open_code_inspect_dialog,
    open_confirm_dialog,
    run_engine_test_dialog,
)

from .step_base import BaseStep

logger = logging.getLogger(__name__)

HELP_TEXT = (
    "- **Review Config**: Review the compiled configuration generated by the "
    "wizard.\n"
    "- **Check Syntax**: Validate INI syntax before persisting.\n"
    "- **Test Config**: Test configuration against digitizer engine and inspect "
    "recognition results.\n"
    "- **Save Config**: Save configuration to `config.ini` and write "
    "reference marker images to disk.\n"
    "- **Take In Use**: Apply the new configuration directly to active "
    "system runtime."
)


class FinalStep(BaseStep):
    def __init__(
        self,
        name: str,
        callbacks: Callbacks,
        set_image_callback: Callable[[str], None],
        save_refs_func: Callable[[], None],
        spinner=None,
    ) -> None:
        super().__init__(
            name,
            set_image_callback=set_image_callback,
            spinner=spinner,
        )
        self.save_refs_func = save_refs_func
        self.callbacks = callbacks
        self.editor: ui.textarea
        self.new_config_saved = False
        self.txt = ""
        self.status_banner = ValidationBanner()

    def update_status_banner(self) -> None:
        self.status_banner.update(self.new_config_saved)

    def _on_editor_changed(self, value: str) -> None:
        if self.new_config_saved and value != self.txt:
            self.new_config_saved = False
            self.update_status_banner()

    def set_config(self, config: Config) -> None:
        self.editor.value = config.save_to_string()
        self.txt = self.editor.value
        self.new_config_saved = False
        self.update_status_banner()

    def _prompt_hot_reload(self) -> None:
        try:
            open_confirm_dialog(
                title="Configuration Saved",
                subtitle="Take new configuration in use?",
                message=(
                    "Configuration and reference templates have been saved to disk. "
                    "Would you like to hot-reload running services now with the new configuration?"
                ),
                confirm_label="Hot Reload Now",
                confirm_icon="autorenew",
                cancel_label="Later",
                color_scheme="blue",
                icon="autorenew",
                on_confirm=self._use_config,
            )
        except Exception as e:
            logger.debug(f"Could not open hot reload dialog: {e}")

    def _save_config(self) -> None:
        if self._syntax_check() is True:
            self.save_refs_func()
            self.callbacks.save_config_file(self.editor.value)
            self.new_config_saved = True
            self.update_status_banner()
            ui.notify("Config saved", type="positive")
            self._prompt_hot_reload()
        self.txt = self.editor.value

    def _show_config(self) -> None:
        try:
            config = Config()
            config.load_from_string(self.editor.value)
            j = config.model_dump_json(indent=4)
            open_code_inspect_dialog(
                title="Compiled Config (JSON)",
                code_content=j,
                language="json",
            )
        except Exception as e:
            ui.notify(f"Syntax error: {e}", type="negative")

    def _use_config(self) -> None:
        self.callbacks.use_config()
        self.new_config_saved = False
        self.update_status_banner()
        ui.notify("Config taken in use", type="positive")
        self.update_status_banner()
        ui.notify("Config taken in use", type="positive")

    def _syntax_check(self) -> bool:
        try:
            config = Config()
            config.load_from_string(self.editor.value)
            ui.notify("Syntax is correct", type="positive")
            return True
        except Exception as e:
            ui.notify(f"Syntax error: {e}", type="negative")
            return False

    async def _test_config(self) -> None:
        try:
            config = Config()
            config.load_from_string(self.editor.value)
        except Exception as e:
            ui.notify(f"Cannot test invalid configuration: {e}", type="negative")
            return

        raw_bytes = None
        if self.image:
            try:
                raw_bytes = base64.b64decode(self.image)
            except Exception:
                raw_bytes = None

        await run_engine_test_dialog(
            config=config,
            callbacks=self.callbacks,
            image_bytes=raw_bytes,
            title_tag="Setup Wizard",
            parent_spinner=self.spinner,
        )

    async def show(self, stepper, first_step=False, last_step=False) -> None:
        with ui.step(self.name):
            self.add_help(HELP_TEXT)

            banner_row = self.status_banner.render(initial_saved=self.new_config_saved)
            banner_row.props('id="final-step-status-banner"')
            banner_row.classes(add="mb-1.5")

            with (
                ui.card().classes(
                    "w-full bg-slate-900/60 border border-white/10 rounded-xl p-2.5 my-1.5"
                ),
                ui.row().classes("w-full items-center justify-between gap-2 flex-wrap"),
            ):
                with ui.row().classes("items-center gap-2"):
                    ui.button(
                        "Check Syntax",
                        icon="verified",
                        on_click=self._syntax_check,
                    ).props("outline dense").classes("text-slate-300 font-medium")

                    ui.button(
                        "Test Config",
                        icon="play_arrow",
                        on_click=self._test_config,
                    ).props("outline dense").classes("text-slate-300 font-medium")

                    ui.button(
                        "JSON Preview",
                        icon="code",
                        on_click=self._show_config,
                    ).props("outline dense").classes("text-slate-300 font-medium")

                with ui.row().classes("items-center gap-2"):
                    self.button_save = (
                        ui.button(
                            "Save Config",
                            icon="save",
                            on_click=self._save_config,
                        )
                        .props("unelevated dense")
                        .classes(
                            "bg-emerald-600 hover:bg-emerald-500 text-white "
                            "px-3 font-medium shadow-md"
                        )
                        .tooltip("Save configuration and marker images to disk")
                    )

                    self.button_use_config = (
                        ui.button(
                            "Take In Use",
                            icon="play_circle",
                            on_click=self._use_config,
                        )
                        .props("unelevated dense")
                        .classes(
                            "bg-gradient-to-r from-blue-600 to-indigo-600 "
                            "hover:from-blue-500 hover:to-indigo-500 text-white "
                            "px-3 font-medium shadow-md"
                        )
                        .tooltip(
                            "Apply configuration immediately to live system runtime"
                        )
                    )

            with ui.card().classes(
                "w-full bg-slate-900/90 border border-white/10 rounded-xl "
                "p-2 my-1.5 shadow-inner"
            ):
                self.editor = (
                    ui.textarea(on_change=lambda e: self._on_editor_changed(e.value))
                    .classes("w-full font-mono text-xs text-slate-200")
                    .props("autoResize rows=22 spellcheck=false")
                )

            self.update_status_banner()
            super().add_navigator(stepper, first_step, last_step)
