import base64
import logging
from collections.abc import Callable

from nicegui import ui

from callbacks import Callbacks
from configuration import Config
from gui.components import (
    ValidationBanner,
    open_code_inspect_dialog,
    open_confirm_dialog,
    run_engine_test_dialog,
)

from .base import BaseStep

logger = logging.getLogger(__name__)


def _build_tooltips(text: str) -> dict[int, str]:
    from gui.pages.config_field_registry import build_line_tooltips

    return build_line_tooltips(text)


def _build_error_decorations(
    text: str, error: Exception
) -> tuple[list[dict], dict[int, str]]:
    from gui.pages.config_field_registry import build_syntax_error_decorations

    return build_syntax_error_decorations(text, error)


HELP_TEXT = (
    "- **Review Config**: Review the compiled configuration generated by the "
    "wizard.\n"
    "- **Check Syntax**: Validate INI syntax before persisting.\n"
    "- **Test Config**: Test configuration against digitizer engine and inspect "
    "recognition results.\n"
    "- **Save Config**: Save configuration to `config.ini` and write "
    "reference marker images to disk.\n"
    "- **Take In Use**: Apply the new configuration directly to active "
    "system runtime."
)


class FinalStep(BaseStep):
    def __init__(
        self,
        name: str,
        callbacks: Callbacks,
        set_image_callback: Callable[[str], None],
        save_refs_func: Callable[[], None],
        spinner=None,
    ) -> None:
        super().__init__(
            name,
            set_image_callback=set_image_callback,
            spinner=spinner,
        )
        self.save_refs_func = save_refs_func
        self.callbacks = callbacks
        self.editor: ui.codemirror
        self.new_config_saved = False
        self.txt = ""
        self.status_banner = ValidationBanner()
        self.deployment_card: ui.card | None = None

    def update_status_banner(self) -> None:
        self.status_banner.update(self.new_config_saved)

    def _on_editor_changed(self, value: str) -> None:
        if hasattr(self, "editor") and self.editor is not None:
            if self.editor.decorations:
                self.editor.decorations = []
            self.editor.line_tooltips = _build_tooltips(value)
        if self.new_config_saved and value != self.txt:
            self.new_config_saved = False
            self.update_status_banner()
            if hasattr(self, "deployment_card") and self.deployment_card is not None:
                self.deployment_card.set_visibility(False)

    def set_config(self, config: Config) -> None:
        self.editor.value = config.save_to_string()
        self.txt = self.editor.value
        self.editor.decorations = []
        self.editor.line_tooltips = _build_tooltips(self.txt)
        self.new_config_saved = False
        self.update_status_banner()
        if hasattr(self, "deployment_card") and self.deployment_card is not None:
            self.deployment_card.set_visibility(False)

    def _prompt_hot_reload(self) -> None:
        try:
            open_confirm_dialog(
                title="Configuration Saved",
                subtitle="Take new configuration in use?",
                message=(
                    "Configuration and reference templates have been saved to disk. "
                    "Would you like to hot-reload running services now with the new configuration?"
                ),
                confirm_label="Hot Reload Now",
                confirm_icon="autorenew",
                cancel_label="Later",
                color_scheme="blue",
                icon="autorenew",
                on_confirm=self._use_config,
            )
        except Exception as e:
            logger.debug(f"Could not open hot reload dialog: {e}")

    def _save_config(self) -> None:
        if self._syntax_check() is True:
            self.save_refs_func()
            self.callbacks.save_config_file(self.editor.value)
            self.new_config_saved = True
            self.update_status_banner()
            ui.notify("Config saved", type="positive")
            self._prompt_hot_reload()
        self.txt = self.editor.value

    def _show_config(self) -> None:
        try:
            config = Config()
            config.load_from_string(self.editor.value)
            j = config.model_dump_json(indent=4)
            open_code_inspect_dialog(
                title="Compiled Config (JSON)",
                code_content=j,
                language="json",
            )
        except Exception as e:
            ui.notify(f"Syntax error: {e}", type="negative")

    def _use_config(self) -> None:
        self.callbacks.use_config()
        self.new_config_saved = False
        self.update_status_banner()
        ui.notify("Config taken in use", type="positive")

    def deploy_configuration(self) -> bool:
        """Validate syntax, save reference images, write config.ini, and hot-reload services."""
        if not self._syntax_check():
            return False
        try:
            # Note: save_refs_func() is called first and is not rolled back if a
            # subsequent step (save_config_file / use_config) raises. Ref images
            # may be written while config.ini is not updated — acceptable because
            # ref images are idempotent and will be overwritten on the next deploy.
            self.save_refs_func()
            self.callbacks.save_config_file(self.editor.value)
            self.callbacks.use_config()
            self.new_config_saved = True
            self.txt = self.editor.value
            self.update_status_banner()
            if hasattr(self, "deployment_card") and self.deployment_card is not None:
                self.deployment_card.set_visibility(True)
            ui.notify(
                "Configuration deployed and services hot-reloaded successfully!",
                type="positive",
            )
            return True
        except Exception as e:
            logger.error(f"Deployment failed: {e}")
            ui.notify(f"Deployment failed: {e}", type="negative")
            return False

    def _syntax_check(self) -> bool:
        try:
            config = Config()
            config.load_from_string(self.editor.value)
            if hasattr(self, "editor") and self.editor is not None:
                self.editor.decorations = []
                self.editor.line_tooltips = _build_tooltips(self.editor.value)
            ui.notify("Syntax is correct", type="positive")
            return True
        except Exception as e:
            if hasattr(self, "editor") and self.editor is not None:
                decorations, tooltips = _build_error_decorations(self.editor.value, e)
                self.editor.decorations = decorations
                self.editor.line_tooltips = tooltips
            ui.notify(f"Syntax error: {e}", type="negative")
            return False

    async def _test_config(self) -> None:
        try:
            config = Config()
            config.load_from_string(self.editor.value)
        except Exception as e:
            ui.notify(f"Cannot test invalid configuration: {e}", type="negative")
            return

        raw_bytes = None
        if self.image:
            try:
                raw_bytes = base64.b64decode(self.image)
            except Exception:
                logger.debug(
                    "Failed to decode base64 image for config testing", exc_info=True
                )
                raw_bytes = None

        await run_engine_test_dialog(
            config=config,
            callbacks=self.callbacks,
            image_bytes=raw_bytes,
            title_tag="Setup Wizard",
            parent_spinner=self.spinner,
        )

    async def show(self, stepper, first_step=False, last_step=False) -> None:
        with ui.step(self.name):
            self.add_help(HELP_TEXT)

            banner_row = self.status_banner.render(initial_saved=self.new_config_saved)
            banner_row.props('id="final-step-status-banner"')
            banner_row.classes(add="mb-1.5")

            with (
                ui.card().classes(
                    "w-full bg-slate-900/60 border border-white/10 rounded-xl p-2.5 my-1.5"
                ),
                ui.row().classes("w-full items-center justify-between gap-2 flex-wrap"),
            ):
                with ui.row().classes("items-center gap-2"):
                    ui.button(
                        "Check Syntax",
                        icon="verified",
                        on_click=self._syntax_check,
                    ).props("outline dense").classes("text-slate-300 font-medium")

                    ui.button(
                        "Test Config",
                        icon="play_arrow",
                        on_click=self._test_config,
                    ).props("outline dense").classes("text-slate-300 font-medium")

                    ui.button(
                        "JSON Preview",
                        icon="code",
                        on_click=self._show_config,
                    ).props("outline dense").classes("text-slate-300 font-medium")

                with ui.row().classes("items-center gap-2"):
                    self.button_save = (
                        ui.button(
                            "Save Config",
                            icon="save",
                            on_click=self._save_config,
                        )
                        .props("unelevated dense")
                        .classes(
                            "bg-emerald-600 hover:bg-emerald-500 text-white "
                            "px-3 font-medium shadow-md"
                        )
                        .tooltip("Save configuration and marker images to disk")
                    )

                    self.button_use_config = (
                        ui.button(
                            "Take In Use",
                            icon="play_circle",
                            on_click=self._use_config,
                        )
                        .props("unelevated dense")
                        .classes(
                            "bg-gradient-to-r from-blue-600 to-indigo-600 "
                            "hover:from-blue-500 hover:to-indigo-500 text-white "
                            "px-3 font-medium shadow-md"
                        )
                        .tooltip(
                            "Apply configuration immediately to live system runtime"
                        )
                    )

                    self.button_deploy = (
                        ui.button(
                            "Validate & Deploy",
                            icon="rocket_launch",
                            on_click=self.deploy_configuration,
                        )
                        .props("unelevated dense")
                        .classes(
                            "bg-gradient-to-r from-emerald-600 via-teal-600 to-cyan-600 "
                            "hover:from-emerald-500 hover:via-teal-500 hover:to-cyan-500 text-white "
                            "px-4 font-bold shadow-lg shadow-teal-950/40"
                        )
                        .tooltip(
                            "Run syntax check, save config & markers, and hot-reload services in one click"
                        )
                    )

            with (
                ui.card()
                .classes(
                    "w-full bg-emerald-950/50 border border-emerald-500/40 rounded-xl "
                    "p-3 my-1.5 flex flex-row items-center justify-between gap-3 shadow-md"
                )
                .props('id="deployment-success-card"') as self.deployment_card,
            ):
                with ui.row().classes("items-center gap-2.5"):
                    ui.icon("check_circle", size="sm").classes(
                        "text-emerald-400 shrink-0"
                    )
                    with ui.column().classes("gap-0"):
                        ui.label("Configuration Active & Deployed").classes(
                            "text-sm font-bold text-emerald-200 leading-tight"
                        )
                        ui.label(
                            "Background reader and services are now running with this configuration."
                        ).classes("text-xs text-emerald-400/80")
                ui.button(
                    "View Live Meter Dashboard",
                    icon="speed",
                    on_click=lambda: ui.navigate.to("/#meter"),
                ).props("unelevated dense").classes(
                    "bg-emerald-600 hover:bg-emerald-500 text-white px-3 py-1 font-semibold text-xs shadow-md shrink-0"
                )
            self.deployment_card.set_visibility(False)

            with ui.card().classes(
                "w-full bg-slate-900/90 border border-white/10 rounded-xl "
                "p-2 my-1.5 shadow-inner"
            ):
                self.editor = (
                    ui.codemirror(
                        on_change=lambda e: self._on_editor_changed(e.value),
                        language="Properties files",  # closest to INI in CodeMirror's language list
                        theme="basicDark",
                        line_wrapping=True,
                    )
                    .classes("w-full")
                    .style("min-height: 400px")
                )
                if self.txt:
                    self.editor.line_tooltips = _build_tooltips(self.txt)

            self.update_status_banner()
            super().add_navigator(stepper, first_step, last_step)
