"""Image processing utilities, format conversions, affine alignment, and filters."""

from __future__ import annotations

from data_classes import ImagePosition, RefImage
from utils.image_filters import (
    adjust_gamma,
    auto_tune_image,
    autocontrast_image,
    calculate_focus_score,
    calculate_histogram,
    convert_to_gray_scale,
    unsharp_mask,
)
from utils.image_glare import (
    apply_clahe,
    apply_illumination_normalize,
    apply_inpaint_glare,
    detect_glare_mask,
    suppress_glare,
)
from utils.image_io import (
    SUPPORTED_IMAGE_FORMATS,
    bytes_to_image,
    convert_base64_str_to_image,
    convert_image_base64str,
    convert_image_to_bytes,
    convert_image_to_np_array,
    convert_np_array_to_image,
    convert_to_image,
    image_size,
    image_size_from_file,
    load_image_from_file,
    save_image,
)
from utils.image_transforms import (
    _get_ref_coordinate,
    adjust_image,
    align,
    align_with_status,
    create_side_by_side_comparison,
    crop_image,
    cut_image,
    draw_rectangle,
    draw_text,
    resize_image,
    rotate,
)

__all__ = [
    "SUPPORTED_IMAGE_FORMATS",
    "ImagePosition",
    "RefImage",
    "_get_ref_coordinate",
    "adjust_gamma",
    "adjust_image",
    "align",
    "align_with_status",
    "apply_clahe",
    "apply_illumination_normalize",
    "apply_inpaint_glare",
    "auto_tune_image",
    "autocontrast_image",
    "bytes_to_image",
    "calculate_focus_score",
    "calculate_histogram",
    "convert_base64_str_to_image",
    "convert_image_base64str",
    "convert_image_to_bytes",
    "convert_image_to_np_array",
    "convert_np_array_to_image",
    "convert_to_gray_scale",
    "convert_to_image",
    "create_side_by_side_comparison",
    "crop_image",
    "cut_image",
    "detect_glare_mask",
    "draw_rectangle",
    "draw_text",
    "image_size",
    "image_size_from_file",
    "load_image_from_file",
    "resize_image",
    "rotate",
    "save_image",
    "suppress_glare",
    "unsharp_mask",
]
